# TCL File Generated by Component Editor 12.1sp1
# Mon Apr 22 17:29:37 CEST 2013
# DO NOT MODIFY


# 
# control_registers_interface "control_registers_interface" v1.0
# null 2013.04.22.17:29:37
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module control_registers_interface
# 
set_module_property NAME control_registers_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME control_registers_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL control_registers_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file control_registers_interface.vhd VHDL PATH control_registers_interface.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point ClkxCI
# 
add_interface ClkxCI clock end
set_interface_property ClkxCI clockRate 50000000
set_interface_property ClkxCI ENABLED true

add_interface_port ClkxCI ClkxCI clk Input 1


# 
# connection point RstxRBI
# 
add_interface RstxRBI reset end
set_interface_property RstxRBI associatedClock ClkxCI
set_interface_property RstxRBI synchronousEdges DEASSERT
set_interface_property RstxRBI ENABLED true

add_interface_port RstxRBI RstxRBI reset_n Input 1


# 
# connection point avalon_slave_1
# 
add_interface avalon_slave_1 avalon end
set_interface_property avalon_slave_1 addressUnits SYMBOLS
set_interface_property avalon_slave_1 associatedClock ClkxCI
set_interface_property avalon_slave_1 associatedReset RstxRBI
set_interface_property avalon_slave_1 bitsPerSymbol 8
set_interface_property avalon_slave_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_1 burstcountUnits WORDS
set_interface_property avalon_slave_1 explicitAddressSpan 0
set_interface_property avalon_slave_1 holdTime 0
set_interface_property avalon_slave_1 linewrapBursts false
set_interface_property avalon_slave_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_1 readLatency 0
set_interface_property avalon_slave_1 readWaitTime 1
set_interface_property avalon_slave_1 setupTime 0
set_interface_property avalon_slave_1 timingUnits Cycles
set_interface_property avalon_slave_1 writeWaitTime 0
set_interface_property avalon_slave_1 ENABLED true

add_interface_port avalon_slave_1 DataOutxDO readdata Output 16
add_interface_port avalon_slave_1 ReadEnxSI read Input 1
add_interface_port avalon_slave_1 WriteEnxSI write Input 1
add_interface_port avalon_slave_1 DataInxDI writedata Input 16
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isPrintableDevice 0

