# TCL File Generated by Component Editor 12.1sp1
# Fri May 10 18:27:26 CEST 2013
# DO NOT MODIFY


# 
# dvi_master_interface "dvi_master_interface" v1.0
# null 2013.05.10.18:27:26
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module dvi_master_interface
# 
set_module_property NAME dvi_master_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME dvi_master_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dvi_master_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dvi_master_interface.vhd VHDL PATH dvi_master_interface.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_main
# 
add_interface clock_main clock end
set_interface_property clock_main clockRate 200000000
set_interface_property clock_main ENABLED true

add_interface_port clock_main ClkxCI clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock_main
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true

add_interface_port reset_n RstxRBI reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_main
set_interface_property avalon_master associatedReset reset_n
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master AmWaitReqxSI waitrequest Input 1
add_interface_port avalon_master AmAddressxDO address Output 32
add_interface_port avalon_master AmReadDataxDI readdata Input 16
add_interface_port avalon_master AmReadxSO read Output 1
add_interface_port avalon_master AmReadDataValidxSI readdatavalid Input 1
add_interface_port avalon_master AmBurstCountxDO burstcount Output 8


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_main
set_interface_property conduit_end associatedReset reset_n
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end ClkDvixCI export Input 1
add_interface_port conduit_end DviNewLinexDI export Input 1
add_interface_port conduit_end DviNewFramexDI export Input 1
add_interface_port conduit_end DviPixelAvxSI export Input 1
add_interface_port conduit_end DviDataOutxDO export Output 16

