# TCL File Generated by Component Editor 12.1
# Wed Feb 20 13:50:55 CET 2013
# DO NOT MODIFY


# 
# stored_interface_block "stored_interface_block" v1.0
# null 2013.02.20.13:50:55
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module stored_interface_block
# 
set_module_property NAME stored_interface_block
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME stored_interface_block
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Stored_Pixel_Interface_block
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file Stored_Pixel_Interface_block.vhd VHDL PATH Stored_Pixel_Interface_block.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master am_WaitRequest waitrequest Input 1
add_interface_port avalon_master am_readdatavalid readdatavalid Input 1
add_interface_port avalon_master am_readdata readdata Input 32
add_interface_port avalon_master am_read read Output 1
add_interface_port avalon_master am_address address Output 32
add_interface_port avalon_master am_burstcount burstcount Output 8


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end DVI_FV export Input 1
add_interface_port conduit_end DVI_LV export Input 1
add_interface_port conduit_end DVI_dataav export Input 1
add_interface_port conduit_end pixelb export Output 8
add_interface_port conduit_end pixelg export Output 8
add_interface_port conduit_end pixelr export Output 8
add_interface_port conduit_end DVI_CLK export Input 1

